### ISSUE TITLE
Custom Keybindings Fail

### ISSUE THREAD

**Issue by brandondrew** [sjurba/rebase-editor#19]
For some reason, the JSON file with keybindings is not being parsed properly.  Here's the error message:

```
$ git rebase --interactive 05ce24982865b1fbedc9f3076cfe4960a0482b5f
/Users/brandon/.rebase:2
  "j": "down",
     ^
SyntaxError: Unexpected token :
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at module.exports (/Users/brandon/.config/yarn/global/node_modules/rebase-editor/lib/key-bindings.js:6:18)
    at module.exports (/Users/brandon/.config/yarn/global/node_modules/rebase-editor/lib/main.js:17:18)
Could not execute editor
```

This happens whether I list only my own keybindings, or only the defaults, or both.  

Here's the relevant line in my `.gitconfig`:

```
editor = rebase-editor --status --color --marker '^Y' --keys ~/.rebase
```

And here is my `~/.rebase` file:

```
{
  "j": "down",
  "k": "up"
}
```

**Comment by sjurba** [comment]
Right. You either need to rename your file to `~/.rebase.json` or make it into a javascript module:
```
module.exports = {
  "j": "down",
  "k": "up"
}
```

The reason is that I simply use `require()` to load the file, and that only works with json when the file is called .json.

I'm closing this issue, but if this doesn't resolve your problem just comment and I'll reopen the issue and take a closer look.
