### ISSUE TITLE
starting editor fails with TypeError: Buffer.allocUnsafe is not a function

### ISSUE THREAD

**Issue by mikosik** [sjurba/rebase-editor#20]
I've installed rebase-editor on Linux Mint 18 Sarah by typing:

```
sudo apt-get install npm
sudo npm install -g rebase-editor
git config --global sequence.editor rebase-editor
```

When I run interactive rebase I receive following error:

```
/usr/bin/env: ‘node’: No such file or directory
Could not execute editor
```

I fixed that by runing (as suggested on some forum)
```
ln -s /usr/bin/nodejs /usr/bin/node
```

And now I got:

```
~/source/hardware $ git ireb HEAD^^^^^^^^^^
/usr/local/lib/node_modules/rebase-editor/node_modules/terminal-kit/lib/ScreenBuffer.js:1495
ScreenBuffer.prototype.CLEAR_BUFFER = Buffer.allocUnsafe( ScreenBuffer.prototype.ITEM_SIZE ) ;
                                             ^

TypeError: Buffer.allocUnsafe is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/rebase-editor/node_modules/terminal-kit/lib/ScreenBuffer.js:1495:46)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/rebase-editor/node_modules/terminal-kit/lib/termkit.js:48:24)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)
Could not execute editor
```

How should I proceed?

**Comment by sjurba** [comment]
Maybe you have an outdated node version? You can check your version with `node --version`

**Comment by mikosik** [comment]
Thanks for quick reply :)

```
~/s/hardware (dev) $ nodejs --version
v4.2.6
```
which version is needed?

**Comment by sjurba** [comment]
The newer the better but anything > 6.0 should work. The latest version is 7.x..

I'll close this issue now, but feel free to reopen it or create a new issue if this doesn't fix your problem.
